services:
  - type: web
    name: ordering-site-demo-jp
    env: docker
    plan: free
    rootDir: .
    region: singapore
    envVars:
      - key: APP_NAME
        value: 発注サイト
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:kO9djMXvBBMWEK1uwRovOnPPkA3Iyx2vuxbL0NTvORw=
      - key: APP_URL
        value: https://ordering-site-demo-jp.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: ordersite-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ordersite-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: ordersite-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: ordersite-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ordersite-db
          property: password

databases:
  - name: ordersite-db
    plan: free
    region: singapore 